#!/bin/bash
# Convert static/* files into C string constants in src/web/static_assets.h
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
STATIC_DIR="$ROOT_DIR/static"
OUT="$ROOT_DIR/src/web/static_assets.h"

echo "Generating $OUT ..."

cat > "$OUT" << 'HEADER'
#ifndef BDTRACE_STATIC_ASSETS_H
#define BDTRACE_STATIC_ASSETS_H

// Auto-generated by scripts/embed_static.sh - DO NOT EDIT

HEADER

for file in "$STATIC_DIR"/*; do
    [ -f "$file" ] || continue
    basename=$(basename "$file")
    varname=$(echo "$basename" | sed 's/[^a-zA-Z0-9]/_/g')

    echo "static const char asset_${varname}[] =" >> "$OUT"

    # Convert file content to C string literals, line by line
    while IFS= read -r line || [ -n "$line" ]; do
        # Escape backslashes, double quotes, and output as C string
        escaped=$(printf '%s' "$line" | sed 's/\\/\\\\/g; s/"/\\"/g')
        echo "    \"${escaped}\\n\"" >> "$OUT"
    done < "$file"

    echo "    ;" >> "$OUT"
    echo "" >> "$OUT"

    # Calculate size
    echo "static const unsigned int asset_${varname}_len = sizeof(asset_${varname}) - 1;" >> "$OUT"
    echo "" >> "$OUT"
done

echo "#endif // BDTRACE_STATIC_ASSETS_H" >> "$OUT"
echo "Done: $OUT"
